### ISSUE TITLE
Debugging/testing protocol version 1.5

### ISSUE THREAD

**Issue by rorycl** [juruen/rmapi#244]
I'm on a remarkable 1 and the new 1.5 protocol support seems to be working fine for me over the last several weeks.

Is there any assistance I can provide in debugging or testing the protocol?

**Comment by ddvk** [comment]
it seems to be ok, i use it with the fake implementation so far without problems. 

there were some minor glitches in the beginning.

just keep on using it and open an issue if something is odd or notwotking as expected.

thanks for the feedback!

**Comment by saccentekennedy** [comment]
I opened an issue (the one prior to this thread). Any ideas on how to resolve it? The warning text is being programmatically read along with the file lists

**Comment by ddvk** [comment]
I merged the fix to master, those will be output to stderr only, so your stdin should be clean

**Comment by saccentekennedy** [comment]
Forgive me, I'm new to phython, etc... Do I have to reinstall RMAPI now?

**Comment by saccentekennedy** [comment]
Yes, I can see I need to. However, as I'm a novice, is there any chance you could update the Windows installer? I don't know how to compile this sort of thing myself! Sorry!!!

**Comment by ddvk** [comment]
ok, test the latest windows release

**Comment by saccentekennedy** [comment]
I'm still getting the same problem. The script I'm using is using this to get a list of files on the reMarkable:

def get_files():
    files_on_remarkable = set([f.split('\t')[-1] for f in rmapi(f"ls {RM_FOLDER}")])
    files_on_local = set()
    for names in os.listdir(ZOTERO_FOLDER):
     if names.endswith(".pdf"):
        files_on_local.add(names)

    return files_on_remarkable, files_on_local

And it is still returning the warning text in the output:

{'WARNING!!!', 'Hassan et al_2018_Is insufficient pulmonary air support the cause of dysphonia in chronic', '  Using the new 1.5 sync, this has not been fully tested yet!!!', 'Ternström et al_2018_FonaDyn — A system for real-time analysis of the electroglottogram, over the', 'Heller Murray et al_2017_The Impact of Glottal Configuration on Speech Breathing', 'Santos et al_2022_Presbylarynx', 'Refreshing tree...', 'Sperry_Klich_1992_Speech Breathing in Senescent and Younger Women During Oral Reading', 'Barsties v. Latoszek et al_2017_The Acoustic Breathiness Index (ABI)', 'Kulbersh et al_2006_Pretreatment, Preoperative Swallowing Exercises May Improve Dysphagia Quality', 'Ternström et al_2019_Update 2', 'Hoit_Hixon_1987_Age and Speech Breathing', '  Make sure you have a backup, in case there is a bug that could cause data loss!', 'Kim_Sapienza_Implications of expiratory muscle strength training for rehabilitation of the'}

Maybe I did something wrong? But I did download the new Windows version of RMAPI as requested. 

Thanks for your help!!

Brian

**Comment by ddvk** [comment]
what is the function rmapi(f'....

**Comment by saccentekennedy** [comment]
Keep in mind, I am trying to alter some code I found elsewhere, but this is how the original coder defined that function...

RMAPI_BIN = args.rmapi  #this defaults to rmapi.exe

def rmapi(cmd):
    return subprocess.check_output(f"{RMAPI_BIN} {cmd}", shell=True, stderr=subprocess.STDOUT).decode("utf-8").split('\n')[0:-1]

**Comment by ddvk** [comment]
remove the: stderr=subprocess.STDOUT

**Comment by saccentekennedy** [comment]
That did it! THANK YOU!

**Comment by ddvk** [comment]
closing as fixed
